pipeline:
  build:
    image: androidsdk/android-30
    commands:
      - pwd #bump
      - ./gradlew assembleDebug --stacktrace

#when:
#repo: Freeyourgadget/Gadgetbridge
#branch: master
#this doesn't work yet:
#https://github.com/woodpecker-ci/woodpecker/issues/687

